const os=require('os');
console.log("freemem:\n",os.freemem());
console.log("homedir:\n",os.homedir());
console.log("hostname:\n",os.hostname());
console.log("endianness:\n",os.endianness());
console.log("loadavg:\n",os.loadavg());
console.log("platform:\n",os.platform());
console.log("release:\n",os.release());
console.log("tmpdir:\n",os.tmpdir());
console.log("totalmem:\n",os.totalmem());
console.log("type:\n",os.type());
console.log("uptime:\n",os.uptime());
console.log("cpus:\n",os.cpus());
console.log("arch:\n",os.arch());
console.log("networkInterfaces:\n",os.networkInterfaces());